from __future__ import annotations


def premium_css() -> str:
    return r'''
<style>
:root{--bg:#020817;--panel:#071327;--card:#0b1b33;--line:rgba(148,163,184,.16);--text:#e6f3ff;--muted:#8aa0b8;--cyan:#22d3ee;--blue:#3b82f6;--green:#4ade80;--purple:#a78bfa}
.stApp{background:radial-gradient(circle at 72% 12%,rgba(34,211,238,.16),transparent 24%),radial-gradient(circle at 20% 90%,rgba(59,130,246,.12),transparent 26%),linear-gradient(180deg,#020817,#061225 58%,#030914)!important;color:var(--text)!important}.block-container{max-width:1400px!important;padding:1.5rem 2.3rem 3rem!important}
div[data-testid="stSidebarContent"]{background:#050d1c!important;border-right:1px solid var(--line)!important}div[data-testid="stSidebarContent"] img{display:none!important}div[data-testid="stSidebarContent"] *{color:var(--text)!important}div[role="radiogroup"] label{border-radius:12px;padding:.35rem .55rem;margin:.15rem 0;border:1px solid transparent}div[role="radiogroup"] label:hover{background:rgba(34,211,238,.07);border-color:rgba(34,211,238,.25)}
.brand-card{border:1px solid rgba(34,211,238,.22);border-radius:20px;background:linear-gradient(135deg,rgba(11,27,51,.95),rgba(7,19,39,.86));padding:1.1rem;margin:.4rem 0 1.25rem;box-shadow:0 22px 70px rgba(0,0,0,.28)}.brand-eyebrow{font-size:.72rem;letter-spacing:.18em;text-transform:uppercase;color:var(--cyan)!important;font-weight:900}.brand-title{font-size:1.8rem;font-weight:950;letter-spacing:-.05em}.brand-sub{font-size:.9rem;color:var(--muted)!important;margin-top:.35rem}
.hero-shell{border:1px solid var(--line);border-radius:28px;background:linear-gradient(135deg,rgba(11,27,51,.92),rgba(3,9,20,.98));overflow:hidden;box-shadow:0 34px 90px rgba(0,0,0,.38);margin-bottom:1.4rem}.hero-top{display:grid;grid-template-columns:1.25fr .95fr;min-height:455px}.hero-main{padding:2.15rem 2.2rem}.kicker{display:inline-flex;border:1px solid rgba(34,211,238,.30);background:rgba(34,211,238,.08);color:var(--cyan);border-radius:999px;padding:.45rem .8rem;font-size:.78rem;letter-spacing:.15em;text-transform:uppercase;font-weight:900;margin-bottom:1.2rem}.hero-line{display:block;font-size:clamp(3.7rem,7vw,6.9rem);font-weight:950;line-height:.9;letter-spacing:-.075em;color:#fff}.hero-copy{font-size:clamp(1.05rem,1.5vw,1.38rem);line-height:1.45;color:var(--muted);max-width:760px;margin-top:1.15rem}.pill{display:inline-block;border:1px solid rgba(148,163,184,.23);border-radius:999px;background:rgba(255,255,255,.05);padding:.55rem .86rem;margin:1.05rem .42rem 0 0;font-size:.82rem;font-weight:850;color:var(--text)}.pill.dark{border:0;background:linear-gradient(90deg,var(--cyan),var(--green));color:#03101c}
.hero-side{padding:1.2rem;background:radial-gradient(circle at 78% 20%,rgba(34,211,238,.22),transparent 30%),rgba(2,8,18,.45)}.console{height:100%;border:1px solid var(--line);border-radius:24px;background:rgba(2,8,18,.72);padding:1.25rem;box-shadow:inset 0 0 80px rgba(34,211,238,.05)}.console-title{font-size:.76rem;letter-spacing:.16em;text-transform:uppercase;color:var(--muted);font-weight:900}.console-big{font-size:3.7rem;font-weight:950;color:#fff;letter-spacing:-.08em;margin:.6rem 0}.console-line{display:flex;justify-content:space-between;border-top:1px solid var(--line);padding:.82rem 0;color:var(--muted)}.console-line strong{color:var(--green)}.node-map{height:145px;position:relative;margin-top:1rem}.node{position:absolute;width:14px;height:14px;border-radius:50%;background:var(--green);box-shadow:0 0 28px var(--green)}.n1{left:18%;top:20%}.n2{left:72%;top:28%}.n3{left:42%;top:62%}.n4{left:84%;top:78%}.wire{position:absolute;height:2px;background:rgba(148,163,184,.42);transform-origin:left}.wire.a{width:160px;left:21%;top:28%;transform:rotate(12deg)}.wire.b{width:120px;left:45%;top:70%;transform:rotate(-24deg)}.wire.c{width:110px;left:21%;top:28%;transform:rotate(58deg)}
.marquee{white-space:nowrap;overflow:hidden;background:rgba(34,211,238,.09);border-top:1px solid var(--line);color:var(--cyan);font-weight:900;letter-spacing:.12em;text-transform:uppercase;padding:.78rem 0}.marquee span{display:inline-block;animation:marquee 18s linear infinite}@keyframes marquee{to{transform:translateX(-50%)}}
.metric-card,.panel{border:1px solid var(--line)!important;background:linear-gradient(180deg,rgba(11,27,51,.88),rgba(7,19,39,.88))!important;color:var(--text)!important;border-radius:22px!important;box-shadow:0 18px 60px rgba(0,0,0,.26)!important}.metric-value{font-size:3rem!important;color:#fff!important}.metric-label,.metric-note,.muted{color:var(--muted)!important}.section-title{color:var(--text)!important;letter-spacing:.12em!important}.stButton>button,.stDownloadButton>button{border:1px solid rgba(34,211,238,.42)!important;background:linear-gradient(90deg,var(--cyan),var(--green))!important;color:#03101c!important;border-radius:999px!important;font-weight:900!important}div[data-testid="stDataFrame"]{border:1px solid var(--line)!important;border-radius:18px!important;overflow:hidden!important}
@media(max-width:950px){.hero-top{grid-template-columns:1fr}.hero-line{font-size:clamp(3rem,14vw,5rem)}.block-container{padding-left:1rem!important;padding-right:1rem!important}}
</style>
'''


def premium_hero(version: str) -> str:
    return f'''
    <div class="hero-shell"><div class="hero-top"><div class="hero-main"><div class="kicker">Open source local network monitoring</div><div class="hero-title-wrap"><span class="hero-line">Monitor your</span><span class="hero-line">local network.</span></div><div class="hero-copy">A clean defensive dashboard for host discovery, service checks, inventory, risk notes, and exportable reports.</div><div><span class="pill dark">v{version}</span><span class="pill">Private IP Only</span><span class="pill">Local Reports</span><span class="pill">Risk Advisor</span></div></div><div class="hero-side"><div class="console"><div class="console-title">Network status</div><div class="console-big">ONLINE</div><div class="console-line"><span>Scope</span><strong>Private LAN</strong></div><div class="console-line"><span>Storage</span><strong>Local</strong></div><div class="console-line"><span>Reports</span><strong>Ready</strong></div><div class="node-map"><div class="wire a"></div><div class="wire b"></div><div class="wire c"></div><div class="node n1"></div><div class="node n2"></div><div class="node n3"></div><div class="node n4"></div></div></div></div></div><div class="marquee"><span>DISCOVER / MONITOR / INSPECT / REPORT / LOCAL ONLY / NETWATCH / DISCOVER / MONITOR / INSPECT / REPORT / LOCAL ONLY / NETWATCH / </span></div></div>
    '''


def premium_sidebar() -> str:
    return '''
    <div class="brand-card"><div class="brand-eyebrow">NetWatch</div><div class="brand-title">Network Monitor</div><div class="brand-sub">Open-source style local visibility</div></div>
    '''
