apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netwatch
resources:
  - kubernetes.yaml
commonLabels:
  netwatch.example.com/operating-model: k3d-local-single-tenant
images:
  - name: your-registry.example/netwatch
    newName: netwatch
    newTag: local
patches:
  - target:
      version: v1
      kind: Service
      name: netwatch
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30080
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: netwatch
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/strategy/type
        value: Recreate
      - op: add
        path: /spec/template/metadata/annotations/netwatch.example.com~1local-boundary
        value: "single-node-k3d-no-ha-no-shared-service"
