from __future__ import annotations

import secrets
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = ROOT / ".env"
DEFAULTS = {
    "NETWATCH_ALLOWED_ORIGINS": "http://127.0.0.1:8000,http://localhost:8000",
    "NETWATCH_API_DOCS": "false",
    "NETWATCH_MAX_CONCURRENT_SCANS": "1",
    "NETWATCH_RATE_LIMIT_REQUESTS": "30",
    "NETWATCH_RATE_LIMIT_WINDOW_SECONDS": "60",
    "NETWATCH_PORT_SCAN_WORKERS": "12",
}


def read_env() -> dict[str, str]:
    values: dict[str, str] = {}
    if not ENV_FILE.exists():
        return values
    for raw_line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def write_env(values: dict[str, str]) -> None:
    ordered = ["NETWATCH_API_KEY", *DEFAULTS.keys()]
    lines = ["# Generated by scripts/start.py. Do not commit this file."]
    for key in ordered:
        lines.append(f"{key}={values[key]}")
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def ensure_configuration() -> str:
    values = read_env()
    current_key = values.get("NETWATCH_API_KEY", "")
    if not current_key or current_key == "replace-with-a-long-random-secret":
        values["NETWATCH_API_KEY"] = secrets.token_urlsafe(32)
    for key, default in DEFAULTS.items():
        values.setdefault(key, default)
    write_env(values)
    return values["NETWATCH_API_KEY"]


def run(command: list[str]) -> None:
    subprocess.run(command, cwd=ROOT, check=True)


def main() -> int:
    api_key = ensure_configuration()
    try:
        run(["docker", "compose", "version"])
        run(["docker", "compose", "up", "-d", "--build", "netwatch"])
    except FileNotFoundError:
        print("Docker was not found. Install Docker Desktop or Docker Engine first.", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        print(f"Docker command failed with exit code {exc.returncode}.", file=sys.stderr)
        return exc.returncode

    print("\nNetWatch is ready.")
    print("URL:     http://127.0.0.1:8000")
    print(f"API key: {api_key}")
    print("The key is also stored in .env and is required by the dashboard connection screen.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
